### ISSUE TITLE
ws endpoint has moved

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1225]
Friday afternoon I noticed that one of the tests was flapping: https://travis-ci.org/ualbertalib/discovery/builds/414706460
```
Failures:
  1) HoldingsHelper holdings with links should return a set of Symphony electronic holdings
     Failure/Error: xml_response ||= open(ws_endpoint+ws_method+ws_parameters+id, :read_timeout => Rails.configuration.symphony_timeout).read
     
     Errno::ETIMEDOUT:
       Connection timed out - connect(2) for "ws.library.ualberta.ca" port 443
     # ./app/services/symphony_service.rb:17:in `initialize'
     # ./app/helpers/holdings_helper.rb:12:in `new'
     # ./app/helpers/holdings_helper.rb:12:in `holdings'
     # ./spec/features/holdings_spec.rb:34:in `block (3 levels) in <top (required)>'
Finished in 2 minutes 9.6 seconds (files took 3.52 seconds to load)
58 examples, 1 failure, 4 pending
Failed examples:
rspec ./spec/features/holdings_spec.rb:31 # HoldingsHelper holdings with links should return a set of Symphony electronic holdings
```
I submitted a help desk ticket to alert the Unix team.  There didn't seem to be any actual disruption but this tidbit was revealed:

> As part of the Symphony migration ws.library.ualberta.ca has moved to
> ils-ws.library.ualberta.ca.

**Comment by pgwillia** [comment]
Received an email titled 'Testing Version 3.5.3' which talks about "upgrade instance is available for testing" 

> ils-upgrade.library.ualberta.ca on port 2306

Neither of these targets seem to work exactly out of the box with the [current code](https://github.com/ualbertalib/discovery/blob/master/app/services/symphony_service.rb#L62). I'm not sure if their meant to either, though.

**Comment by pgwillia** [comment]
Not currently an issue.  Close for now.
